### ISSUE TITLE
Publishing Azure Web App fails if the target is running on a Linux App Service Plan

### ISSUE THREAD

**Issue by johnnyegel** [JetBrains/azure-tools-for-intellij#271]
If you try to publish an Azure Web App to an Azure App Service which use a Linux Service Plan, the publishing fails. The following output is found in the log view:

```
Got existing Web App with Id: '/subscriptions/xxxxx/resourceGroups/yyyyy/providers/Microsoft.Web/sites/deviceownerregistry'
Collecting 'HomeDisplayOwnerRegistry' project artifacts...
Creating 'HomeDisplayOwnerRegistry' project ZIP...
Project ZIP is created: '/tmp/rider-publish3830211185482384892.zip'
Stop Web App 'deviceownerregistry'...
Publishing ZIP file. Attempt 1 of 3...
Publishing ZIP file. Attempt 2 of 3...
Publishing ZIP file. Attempt 3 of 3...
Fail publishing ZIP file: Response code: 500. Response message: Internal Server Error
Fail publishing ZIP file: java.lang.RuntimeException: Fail publishing ZIP file: Response code: 500. Response message: Internal Server Error
Fail publishing ZIP file
```

**Comment by maartenba** [comment]
Issue has been fixed, we'll publish a new build of the plugin today.

**Comment by profimedica** [comment]
Still not fixed. I get Response code: 400. Response message: Bad Request.

Collecting 'Ajuro.Micro.Public' project artifacts...
Creating 'Ajuro.Micro.Public' project ZIP...
Project ZIP is created: '/tmp/rider-publish11578605463174886711.zip'
Stop Web App 'OtbExpert'...
Publishing ZIP file. Attempt 1 of 3...
Publishing ZIP file. Attempt 2 of 3...
Publishing ZIP file. Attempt 3 of 3...
Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
Fail publishing ZIP file: java.lang.RuntimeException: Fail publishing ZIP file. Response code: 400. Response message: Bad Request.

**Comment by MpStyle** [comment]
I have the same issue. Any updates?

**Comment by maartenba** [comment]
@MpStyle the issue should be resolved in 2021.3 EAP - feel free to give it a try (preview, will be released ~end November)
www.jetbrains.com/rider/eap

**Comment by eneance-alorenzi** [comment]
Still not fixed in EAP (Rider)

**Comment by maartenba** [comment]
What error do you get?

**Comment by eneance-alorenzi** [comment]
Hello,

Rider version : JetBrains Rider 2021.3 EAP 8, Build #RD-213.5744.78, built on November 13, 2021
Azure toolkit version : 3.50.0.1306-2021.3
(same result on stable versions)

I'm on a M1 macbook pro.

Here's the messages (trying to publish on a Linux Azure WebApp) :

Project ZIP is created: '/private/var/folders/yw/ddml49_56z5cfpj7vgqzzlbm0000gn/T/rider-publish13079648125336562918.zip'
Stop Web App 'eneance-usr-dev'...
Publishing ZIP file. Attempt 1 of 3...
Publishing ZIP file. Attempt 2 of 3...
Publishing ZIP file. Attempt 3 of 3...
Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
Fail publishing ZIP file: java.lang.RuntimeException: Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
Fail publishing ZIP file


Publishing works with Visual Studio on Windows...

**Comment by eneance-alorenzi** [comment]
And the code I'm trying to publish is a .net 5 WebAPI

**Comment by eneance-alorenzi** [comment]
java.lang.Throwable: Fail publishing ZIP file: java.lang.RuntimeException: Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.microsoft.intellij.runner.webapp.config.runstate.WebAppDeployStateUtil.packAndDeploy(WebAppDeployStateUtil.kt:207)
	at com.microsoft.intellij.runner.webapp.config.runstate.WebAppDeployStateUtil.deployToAzureWebApp(WebAppDeployStateUtil.kt:126)
	at com.microsoft.intellij.runner.webapp.config.RiderWebAppRunState.executeSteps(RiderWebAppRunState.kt:97)
	at com.microsoft.intellij.runner.webapp.config.RiderWebAppRunState.executeSteps(RiderWebAppRunState.kt:60)
	at com.microsoft.azure.toolkit.intellij.common.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:60)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$0(AzureRxTaskManager.java:30)
	at com.microsoft.azure.toolkit.lib.common.task.AzureTaskContext.run(AzureTaskContext.java:78)
	at com.microsoft.azure.toolkit.lib.common.task.AzureRxTaskManager.lambda$null$1(AzureRxTaskManager.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by maartenba** [comment]
The 400 error means Azure refused the deployment. I'll investigate if we can get a good error message out of it.

Meanwhile by any chance, is the web app configured with deployment via Git or other SCM? Can you try on a newly created web app?

**Comment by eneance-alorenzi** [comment]
Dear Maarten,

Thanks for your help.

The "old" webApp has always been deployed manually (we only configure CI/CD on non development env), but by different ways : rider on mac (both intel & M1 chip), visual studio on mac (both intel &M1 chip), visual studio on windows... and it worked... I just installed a new macbook pro M1 max, with latest version of all tools... and deployment failed.

As you suggested, I've created a new web app on Azure, and manual deployment with rider on mac works !

Maybe using different manual ways to deploy broke something...

Thanks for your time and the suggestion

**Comment by MpStyle** [comment]
Still not fixed in JetBrains Rider 2021.3.1 and Azure Toolkit for Rider 3.50.0.1312-2021.3.
I'm trying to publish is a .net 5 WebAPI.

The error is the same:
_Collecting 'XXX' project artifacts...
Creating 'XXX' project ZIP...
Project ZIP is created: 'XXX/rider-publish12661628730084922865.zip'
Stop Web App 'XXX'...
Publishing ZIP file. Attempt 1 of 3...
Publishing ZIP file. Attempt 2 of 3...
Publishing ZIP file. Attempt 3 of 3...
Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
Fail publishing ZIP file: java.lang.RuntimeException: Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
Fail publishing ZIP file_

**Comment by maartenba** [comment]
@MpStyle is this for an existing web app that had deployments before? Is this the case for a new web app as well?

**Comment by DetonatorB** [comment]
I still see this too. Rider 2021.3.1, Azure Toolkit for Rider 3.50.0.1312-2021.3.
It's very, very frustrating to have to resort to Visual Studio again just for publishing this app.
The Azure Web App I am publishing to is an existing WebApp on Linux and in a slot.
I cannot easily create a new slot because of other users, scripts and a lot of configuration work.

**What do you need from me to diagnose this issue?**

Collecting 'xxx' project artifacts...
Creating 'xxx' project ZIP...
Project ZIP is created: 'C:\Users\xxx~1\AppData\Local\Temp\rider-publish10269327809348642708.zip'
Stop Web App 'staging'...
Publishing ZIP file. Attempt 1 of 3...
Publishing ZIP file. Attempt 2 of 3...
Publishing ZIP file. Attempt 3 of 3...
Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
Fail publishing ZIP file: java.lang.RuntimeException: Fail publishing ZIP file. Response code: 400. Response message: Bad Request.
Fail publishing ZIP file

[Edit] It is a .net 5 aspnet mvc app and is configered as such in Azure.

**Comment by maartenba** [comment]
@DetonatorB is this for an existing web app that had deployments before? Is this the case for a new web app as well?

We do a ZIP publish (not web publish like VS) where the API Azure offers returns a 400 in some cases where the site already has a deployment with a different mechanism.

**Comment by DetonatorB** [comment]
@maartenba Yes, this is an existing application that has been updated many times, using Visual Studio 2019. Because this is a aspnet core web app running on the Linux Azure Web App offer, VS2019 also uses Zip Deploy BTW (see below).
I will try deploying to a new Web App later this week, but AFAICS other have reported this *does* work with Rider, but in turn inhibits updates by VS.

Visual Studio 2019 output during successful publish of the same project:

19>Done building project "xxx.xxx.csproj".
20>------ Publish started: Project: xxx.xxx, Configuration: Release Any CPU ------

Bundler: Begin processing bundleconfig.json
Bundler: Done processing bundleconfig.json
xxx.xxx-> D:\live\xxx\src\xxx-core\xxx.xxx\bin\Release\net5.0\xxx.xxx.dll
xxx.xxx-> D:\live\xxx\src\xxx-core\xxx.xxx\bin\Release\net5.0\xxx.xxx.Views.dll
xxx.xxx-> D:\live\xxx\src\xxx-core\xxx.xxx\obj\Release\net5.0\PubTmp\Out\
Publishing D:\live\xxx\src\xxx-core\xxx.xxx\obj\Release\net5.0\PubTmp\xxx.xxx-20211222020624876.zip to https://xxx.scm.azurewebsites.net/api/zipdeploy...
Zip Deployment succeeded.
========== Build: 19 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========
Waiting for Web App to be ready...
Restarting the Web App...
Successfully restarted Web App.
Web App is ready.

**Comment by MpStyle** [comment]
> @MpStyle is this for an existing web app that had deployments before? Is this the case for a new web app as well?

it is an existing web app that has deployed before

**Comment by maartenba** [comment]
I have not yet been able to reproduce the issue, but have an experimental build of the plugin that _may_ resolve the issue (based on the hint in https://github.com/microsoft/azure-pipelines-tasks/issues/8657#issuecomment-432530739 and what the Kudu service URL looks like here https://github.com/projectkudu/kudu/blob/master/Kudu.Services/Deployment/PushDeploymentController.cs#L367).

@MpStyle @DetonatorB would you be willing to give it a try? Note it is compatible with 2021.3 only.

* Uninstall the Azure plugin from Rider
* Download the plugin ZIP archive from our build server here: https://teamcity.jetbrains.com/repository/download/JetBrainsPublicProjects_AzureToolsForIntellij_BuildPluginSd/3744351:id/azure-toolkit-for-rider-3.50.0.1313-2021.3.zip (use "Log in as guest" if any auth is requested)
* Install "from disk" using these instructions: https://www.jetbrains.com/help/rider/Managing_Plugins.html#install_plugin_from_disk

**Comment by MpStyle** [comment]
@maartenba it works! Thank you so much!
What was the problem?

```
Collecting 'XXXXXXX' project artifacts...
Creating 'XXXXXXX' project ZIP...
Project ZIP is created: '/XXXXXXX.zip'
Stop Web App 'XXXXXXX'...
Publishing ZIP file. Attempt 1 of 3...
Fail publishing ZIP file: java.net.SocketTimeoutException: timeout
Publishing ZIP file. Attempt 2 of 3...
Published ZIP file successfully
Deleting ZIP file '/XXXXXXX.zip'...
Deploy succeeded.
Start Web App 'XXXXXXX'...
URL: https://XXXXXXX.azurewebsites.net
Done.
```

**Comment by DetonatorB** [comment]
@maartenba Yep, that did it. You're gold. Thank you for fixing this. This solves *so* many problems.
And many thanks to @vincent1173 as well for noticing the errant content types.

**Comment by maartenba** [comment]
Thanks @DetonatorB and @MpStyle for testing!

The issue was really this - https://github.com/microsoft/azure-pipelines-tasks/issues/8657#issuecomment-432530739 - the content type was not specified causing some of the Azure API versions to fail on upload. The fix is this fantastic one-liner :D https://github.com/JetBrains/azure-tools-for-intellij/pull/554/files#diff-5cf117ae2c17f91b8a7953b056707c14c7dcb3ae46d21abcd83875bd9dee12e7R79

Will push this through the rest of the process and get a new version released in the coming days.

**Comment by ScottKane** [comment]
Still not fixed, getting the following trying to deploy a .NET 6 web app on a linux plan in Rider 2022.1.2:

```
Collecting 'Server' project artifacts...
Creating 'Server' project ZIP...
Project ZIP is created: 'C:\Users\scott\AppData\Local\Temp\rider-publish10281568581793079241.zip'
Publishing ZIP file. Attempt 1 of 3...
Fail publishing ZIP file: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
Publishing ZIP file. Attempt 2 of 3...
Fail publishing ZIP file: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
Publishing ZIP file. Attempt 3 of 3...
Fail publishing ZIP file: okhttp3.internal.http2.StreamResetException: stream was reset: NO_ERROR
Fail publishing ZIP file. Response code: null. Response message: null.
Fail publishing ZIP file: java.lang.RuntimeException: Fail publishing ZIP file. Response code: null. Response message: null.
Fail publishing ZIP file
```

Also got a 502 in a previous attempt

**Comment by maartenba** [comment]
@ScottKane Would you mind trying with the 2022.2 EAP? (although that `StreamResetException` looks like connectivity issues reaching the Azure API)

**Comment by ScottKane** [comment]
@maartenba This happened when I was trying to deploy a gRPC service following this https://github.com/Azure/app-service-linux-docs/blob/master/HowTo/gRPC/use_gRPC_with_dotnet.md, I assume some of the changes required to the service to allow the http2 proxy are what caused the issues. I didn't have any issues publishing the same service from VS though and have been able to push normal none http2 apps to azure.
